name: Unit Tests Runner

on: [pull_request,push]

jobs: 
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Packagers
        run: npm install
      - name: Run Lint
        run: npm run lint
      - name: Run Test
        run: npm run test
